# Generated by Django 2.0 on 2018-05-25 19:56

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180525_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
